# 基础镜像
FROM golang:1.10

# 维护者
MAINTAINER fenggese "18852852150@163.com"

# beego开发
RUN go get github.com/astaxie/beego
RUN go get github.com/beego/bee

# mysql 
RUN go get -u github.com/go-sql-driver/mysql

# redis
RUN go get github.com/gomodule/redigo/redis


